import { CatalogItem } from '@/types';

export function buildCatalogItems(): CatalogItem[] {
  return [
    {
      id: 'subject-listing',
      label: 'Subject Listing',
      description: 'Demographics & study status',
      type: 'subject-listing',
      category: 'SUBJECT',
      visualizationType: 'table',
    },
    {
      id: 'patient-profile',
      label: 'Patient Profile',
      description: 'Full subject cross-domain view',
      type: 'patient-profile',
      category: 'SUBJECT',
      visualizationType: 'table',
    },
    {
      id: 'ae-timeline',
      label: 'AE Timeline',
      description: 'Adverse event swim lane',
      type: 'ae-timeline',
      category: 'SAFETY',
      visualizationType: 'chart',
    },
    {
      id: 'ae-summary',
      label: 'AE Summary',
      description: 'AE term frequency chart',
      type: 'ae-summary',
      category: 'SAFETY',
      visualizationType: 'chart',
    },
    {
      id: 'conmed',
      label: 'CONMED',
      description: 'Concomitant medications',
      type: 'conmed',
      category: 'MEDICATIONS',
      visualizationType: 'table',
    },
    {
      id: 'med-history',
      label: 'Med History (MH)',
      description: 'Prior conditions by subject',
      type: 'med-history',
      category: 'MEDICAL HISTORY',
      visualizationType: 'table',
    },
    {
      id: 'lab-trend',
      label: 'Lab Trend',
      description: 'ALT trend — all subjects',
      type: 'lab-trend',
      category: 'LABS & VITALS',
      visualizationType: 'chart',
    },
    {
      id: 'lab-listing',
      label: 'Lab Listing',
      description: 'Lab results table with flags',
      type: 'lab-listing',
      category: 'LABS & VITALS',
      visualizationType: 'table',
    },
    {
      id: 'vital-signs',
      label: 'Vital Signs',
      description: 'BP, HR over time',
      type: 'vital-signs',
      category: 'LABS & VITALS',
      visualizationType: 'chart',
    },
    {
      id: 'visit-grid',
      label: 'Visit Grid',
      description: 'Visit completion heatmap',
      type: 'visit-grid',
      category: 'VISITS',
      visualizationType: 'table',
    },
    {
      id: 'exposure',
      label: 'Exposure (EX)',
      description: 'Dosing & treatment exposure',
      type: 'exposure',
      category: 'EXPOSURE',
      visualizationType: 'table',
    },
    {
      id: 'dm-concierge',
      label: 'DM Concierge',
      description: 'Ask questions about study data',
      type: 'dm-concierge',
      category: 'AI ASSISTANT',
      visualizationType: 'table',
    },
    {
      id: 'site-enrollment',
      label: 'Site Enrollment',
      description: 'Enrollment by site over time',
      type: 'site-enrollment',
      category: 'OPERATIONS',
      visualizationType: 'chart',
    },
  ];
}
